defmodule Packheavy.Repo.Migrations.AddInventoryAndTrips do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trips, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :start_date, :date
      add :end_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "draft"

      add :user_id,
          references(:users,
            column: :id,
            name: "trips_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:trip_kits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trip_id,
          references(:trips,
            column: :id,
            name: "trip_kits_trip_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :kit_id, :uuid, null: false
    end

    create unique_index(:trip_kits, [:trip_id, :kit_id], name: "trip_kits_unique_trip_kit_index")

    create table(:trip_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :qty, :bigint, null: false, default: 1
      add :source, :text, null: false, default: "direct"
      add :source_kit_id, :uuid
      add :packed, :boolean, null: false, default: false
      add :charged, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trip_id,
          references(:trips,
            column: :id,
            name: "trip_items_trip_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :item_id, :uuid, null: false
    end

    create table(:kits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:trip_kits) do
      modify :kit_id,
             references(:kits,
               column: :id,
               name: "trip_kits_kit_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:kits) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "kits_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:kit_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :qty, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :kit_id,
          references(:kits,
            column: :id,
            name: "kit_items_kit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :item_id, :uuid, null: false
    end

    create unique_index(:kit_items, [:kit_id, :item_id], name: "kit_items_unique_kit_item_index")

    create table(:items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:trip_items) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "trip_items_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:kit_items) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "kit_items_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:items) do
      add :title, :text, null: false
      add :weight_g, :bigint, null: false, default: 0
      add :notes, :text
      add :category_data, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "items_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:cable_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "cable_types_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:cable_types, [:name, :user_id], name: "cable_types_name_per_user_index")

    create table(:battery_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "battery_types_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:battery_types, [:name, :user_id],
             name: "battery_types_name_per_user_index"
           )
  end

  def down do
    drop constraint(:battery_types, "battery_types_user_id_fkey")

    drop_if_exists unique_index(:battery_types, [:name, :user_id],
                     name: "battery_types_name_per_user_index"
                   )

    drop table(:battery_types)

    drop constraint(:cable_types, "cable_types_user_id_fkey")

    drop_if_exists unique_index(:cable_types, [:name, :user_id],
                     name: "cable_types_name_per_user_index"
                   )

    drop table(:cable_types)

    drop constraint(:items, "items_user_id_fkey")

    alter table(:items) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :category_data
      remove :notes
      remove :weight_g
      remove :title
    end

    drop constraint(:kit_items, "kit_items_item_id_fkey")

    alter table(:kit_items) do
      modify :item_id, :uuid
    end

    drop constraint(:trip_items, "trip_items_item_id_fkey")

    alter table(:trip_items) do
      modify :item_id, :uuid
    end

    drop table(:items)

    drop constraint(:kit_items, "kit_items_kit_id_fkey")

    drop_if_exists unique_index(:kit_items, [:kit_id, :item_id],
                     name: "kit_items_unique_kit_item_index"
                   )

    drop table(:kit_items)

    drop constraint(:kits, "kits_user_id_fkey")

    alter table(:kits) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:trip_kits, "trip_kits_kit_id_fkey")

    alter table(:trip_kits) do
      modify :kit_id, :uuid
    end

    drop table(:kits)

    drop constraint(:trip_items, "trip_items_trip_id_fkey")

    drop table(:trip_items)

    drop constraint(:trip_kits, "trip_kits_trip_id_fkey")

    drop_if_exists unique_index(:trip_kits, [:trip_id, :kit_id],
                     name: "trip_kits_unique_trip_kit_index"
                   )

    drop table(:trip_kits)

    drop constraint(:trips, "trips_user_id_fkey")

    drop table(:trips)
  end
end
