defmodule Packheavy.Repo.Migrations.DropLegacyTripStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trips) do
      remove :hiker_weight_kg
      remove :elevation_gain_m
      remove :distance_km
    end
  end

  def down do
    alter table(:trips) do
      add :distance_km, :decimal
      add :elevation_gain_m, :bigint
      add :hiker_weight_kg, :decimal
    end
  end
end
