defmodule Packheavy.Repo.Migrations.TripPlannerPhase1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text
      add :phone, :text
      add :satellite_sms, :text
      add :location_tracker_url, :text
      add :location_tracker_password, :text
      add :default_hiker_weight_kg, :decimal
      add :default_hiker_notes, :text
    end

    alter table(:trips) do
      add :area, :text
      add :park_url, :text
      add :route_url, :text
      add :departure_at, :utc_datetime
      add :return_at, :utc_datetime
      add :escalation_criteria, :text
      add :gear_highlights, :text
    end

    create table(:trip_hikers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :role, :text, null: false, default: "member"
      add :phone, :text
      add :satellite_sms, :text
      add :location_tracker_url, :text
      add :location_tracker_password, :text
      add :weight_kg, :decimal
      add :notes, :text
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trip_id,
          references(:trips,
            column: :id,
            name: "trip_hikers_trip_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "trip_hikers_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:trip_contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :relationship, :text
      add :phone, :text
      add :kind, :text, null: false
      add :escalation_criteria, :text
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trip_id,
          references(:trips,
            column: :id,
            name: "trip_contacts_trip_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    # Backfill: seed a leader TripHiker for every existing trip,
    # copying trip.hiker_weight_kg into the new TripHiker.weight_kg.
    # Name comes from the user's profile name, falling back to their
    # email so older records stay readable. Skips trips that somehow
    # already have a hiker (idempotency for partial reruns).
    execute("""
    INSERT INTO trip_hikers
      (id, trip_id, user_id, name, role, weight_kg, position, inserted_at, updated_at)
    SELECT
      gen_random_uuid(),
      t.id,
      t.user_id,
      COALESCE(NULLIF(u.name, ''), u.email::text, 'Hiker'),
      'leader',
      t.hiker_weight_kg,
      0,
      now() AT TIME ZONE 'utc',
      now() AT TIME ZONE 'utc'
    FROM trips t
    JOIN users u ON u.id = t.user_id
    WHERE NOT EXISTS (
      SELECT 1 FROM trip_hikers th WHERE th.trip_id = t.id
    )
    """)
  end

  def down do
    drop constraint(:trip_contacts, "trip_contacts_trip_id_fkey")

    drop table(:trip_contacts)

    drop constraint(:trip_hikers, "trip_hikers_trip_id_fkey")

    drop constraint(:trip_hikers, "trip_hikers_user_id_fkey")

    drop table(:trip_hikers)

    alter table(:trips) do
      remove :gear_highlights
      remove :escalation_criteria
      remove :return_at
      remove :departure_at
      remove :route_url
      remove :park_url
      remove :area
    end

    alter table(:users) do
      remove :default_hiker_notes
      remove :default_hiker_weight_kg
      remove :location_tracker_password
      remove :location_tracker_url
      remove :satellite_sms
      remove :phone
      remove :name
    end
  end
end
