defmodule Packheavy.Repo.Migrations.PlbFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :plb_hex_id, :text
      add :plb_serial, :text
    end

    alter table(:trip_hikers) do
      add :plb_hex_id, :text
      add :plb_serial, :text
    end
  end

  def down do
    alter table(:trip_hikers) do
      remove :plb_serial
      remove :plb_hex_id
    end

    alter table(:users) do
      remove :plb_serial
      remove :plb_hex_id
    end
  end
end
