defmodule Packheavy.Repo.Migrations.TripShareToken do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trips) do
      add :share_token, :text
    end

    create unique_index(:trips, [:share_token], name: "trips_share_token_index")
  end

  def down do
    drop_if_exists unique_index(:trips, [:share_token], name: "trips_share_token_index")

    alter table(:trips) do
      remove :share_token
    end
  end
end
