defmodule Packheavy.Repo.Migrations.AddItemBrand do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add :brand, :text
    end
  end

  def down do
    alter table(:items) do
      remove :brand
    end
  end
end
