defmodule Packheavy.Repo.Migrations.DaySidequestCarryMode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trip_legs) do
      add :day, :bigint, null: false, default: 1
      add :sidequest, :boolean, null: false, default: false
    end

    alter table(:trip_items) do
      add :carry_mode, :text, null: false, default: "main_pack"
    end
  end

  def down do
    alter table(:trip_items) do
      remove :carry_mode
    end

    alter table(:trip_legs) do
      remove :sidequest
      remove :day
    end
  end
end
