defmodule Packheavy.Repo.Migrations.Tested do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trip_items) do
      add :tested, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:trip_items) do
      remove :tested
    end
  end
end
