defmodule Packheavy.Repo.Migrations.TripLegs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trip_legs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :name, :text, null: false
      add :gpx_filename, :text
      add :distance_m, :float, null: false
      add :elevation_gain_m, :float, null: false
      add :point_count, :bigint, null: false
      add :track, {:array, :map}, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trip_id,
          references(:trips,
            column: :id,
            name: "trip_legs_trip_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:trip_legs, [:trip_id, :position],
             name: "trip_legs_unique_position_per_trip_index"
           )
  end

  def down do
    drop constraint(:trip_legs, "trip_legs_trip_id_fkey")

    drop_if_exists unique_index(:trip_legs, [:trip_id, :position],
                     name: "trip_legs_unique_position_per_trip_index"
                   )

    drop table(:trip_legs)
  end
end
