defmodule Packheavy.Repo.Migrations.BatteryRechargeableAndElectronicPowerSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:battery_types) do
      add :rechargeable, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:battery_types) do
      remove :rechargeable
    end
  end
end
