defmodule Packheavy.Repo.Migrations.CascadeDeleteItemRefs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:trip_kits, "trip_kits_kit_id_fkey")

    alter table(:trip_kits) do
      modify :kit_id,
             references(:kits,
               column: :id,
               name: "trip_kits_kit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:trip_items, "trip_items_item_id_fkey")

    alter table(:trip_items) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "trip_items_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:kit_items, "kit_items_item_id_fkey")

    alter table(:kit_items) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "kit_items_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:kit_items, "kit_items_item_id_fkey")

    alter table(:kit_items) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "kit_items_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:trip_items, "trip_items_item_id_fkey")

    alter table(:trip_items) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "trip_items_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:trip_kits, "trip_kits_kit_id_fkey")

    alter table(:trip_kits) do
      modify :kit_id,
             references(:kits,
               column: :id,
               name: "trip_kits_kit_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
