defmodule Packheavy.Repo.Migrations.LegPace do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trip_legs) do
      add :pace_kmh, :float, null: false, default: 4.0
    end
  end

  def down do
    alter table(:trip_legs) do
      remove :pace_kmh
    end
  end
end
