defmodule Packheavy.Repo.Migrations.ItemQty do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add :qty, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:items) do
      remove :qty
    end
  end
end
